version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: syncboard-postgres
    environment:
      POSTGRES_DB: syncboard
      POSTGRES_USER: syncboard
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - syncboard-network

  redis:
    image: redis:7-alpine
    container_name: syncboard-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - syncboard-network

  adminer:
    image: adminer:latest
    container_name: syncboard-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - syncboard-network
    depends_on:
      - postgres

  # Optional: MinIO for S3-compatible storage in development
  minio:
    image: minio/minio:latest
    container_name: syncboard-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - syncboard-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  syncboard-network:
    driver: bridge 